Repository BinaryStudioAcademy/bsa-winter-2022-2023-easyspeak, pull requests merged in 2023-04, with the labels that each got.

#118 Fixed dropdown arrow gap to right side according to design
  frontend/src/app/modules/auth/auth-page/auth-page.component.sass
Labels: bugfix

#120 fixed a bug with error messages
  frontend/src/app/modules/auth/auth-page/auth-page.component.sass
  frontend/src/app/modules/auth/sign-in/sign-in.component.sass
  frontend/src/app/modules/auth/sign-up/sign-up.component.sass
Labels: bugfix

#122 Fixed a bug with links in header)
  frontend/src/app/shared/components/header/header.component.html
Labels: bugfix

#123 some bugfix on chat page
  frontend/src/app/modules/chat/chat-page/chat-page.component.sass
  frontend/src/app/modules/chat/chat-page/chat-page.component.ts
  frontend/src/app/modules/chat/message-group/message-group.component.sass
Labels: bugfix

#117 150 youtube player preview image fixed
  frontend/src/app/modules/lessons/lesson/lesson.component.html
  frontend/src/app/modules/lessons/lesson/lesson.component.sass
  frontend/src/app/modules/lessons/lesson/lesson.component.ts
  frontend/src/assets/lesson-icons/no-video.png
Labels: bugfix

#129 138 154 157 167 fixed all bugs related to create lesson component
  frontend/src/app/modules/lessons/lesson/lesson.component.sass
  frontend/src/app/modules/lessons/lessons-create/lessons-create.component.html
  frontend/src/app/modules/lessons/lessons-create/lessons-create.component.sass
  frontend/src/app/shared/components/interests-dropdown/interests-dropdown.component.sass
Labels: bugfix

#133 changed font-weight on select topic page
  frontend/src/app/modules/user-profile/select-topics-page/select-topics-page.component.sass
Labels: bugfix

#137 178 enormous scrollbar bugfix
  frontend/src/styles/scrollbar.sass
Labels: bugfix

#139 fix user request
  frontend/src/app/core/services/auth.service.ts
  frontend/src/app/modules/auth/sign-up/sign-up.component.ts
Labels: bugfix

#146 fixed bug with buttob and text location
  frontend/src/app/modules/lessons/lesson/lesson.component.html
  frontend/src/app/modules/lessons/lesson/lesson.component.sass
Labels: bugfix

#144 Fixed a bug with header in not found page
  frontend/src/app/app-routing.module.ts
  frontend/src/app/modules/main/main-routing.module.ts
  frontend/src/app/shared/components/not-found/not-found.component.html
Labels: bugfix

#96 32 forgot password page
  frontend/src/app/core/services/auth.service.ts
  frontend/src/app/modules/auth/auth-routing.module.ts
  frontend/src/app/modules/forgot-password/change-password/change-password.component.html
  frontend/src/app/modules/forgot-password/change-password/change-password.component.sass
  frontend/src/app/modules/forgot-password/change-password/change-password.component.ts
  frontend/src/app/modules/forgot-password/check-email/check-email.component.html
  frontend/src/app/modules/forgot-password/check-email/check-email.component.sass
  frontend/src/app/modules/forgot-password/check-email/check-email.component.ts
  frontend/src/app/modules/forgot-password/forgot-password-page/forgot-password-page.component.html
  frontend/src/app/modules/forgot-password/forgot-password-page/forgot-password-page.component.sass
  frontend/src/app/modules/forgot-password/forgot-password-page/forgot-password-page.component.ts
  frontend/src/app/modules/forgot-password/forgot-password-routing.module.ts
  frontend/src/app/modules/forgot-password/forgot-password.module.ts
  frontend/src/app/modules/forgot-password/write-email/write-email.component.html
  frontend/src/app/modules/forgot-password/write-email/write-email.component.sass
  frontend/src/app/modules/forgot-password/write-email/write-email.component.ts
  frontend/src/app/shared/data/regex.util.ts
  frontend/src/assets/forgot-password-icons/ClosedMailboxWithRaisedFlag.svg
  frontend/src/assets/forgot-password-icons/EMail.svg
  frontend/src/assets/forgot-password-icons/FaceWithSteamFromNose.svg
  frontend/src/assets/forgot-password-icons/IncomingEnvelope.svg
  frontend/src/assets/forgot-password-icons/Key.svg
  frontend/src/assets/forgot-password-icons/MagnifyingGlassTiltedRight.svg
  frontend/src/assets/forgot-password-icons/Pencil.svg
  frontend/src/assets/forgot-password-icons/ThinkingFace.svg
  frontend/src/assets/forgot-password-icons/alert-triangle.svg
  frontend/src/assets/forgot-password-icons/eye-off.svg
Labels: enhancement

#140 112 Fixed start at date in lessons
  frontend/src/app/models/lessons/lesson.ts
  frontend/src/app/modules/lessons/lesson/lesson.component.html
  frontend/src/app/modules/lessons/lessons-page/lessons-page.component.ts
Labels: bugfix

#148 125 176 saving private calendar
  backend/EasySpeak.Core/EasySpeak.Core.Common/DTO/User/NewUserDto.cs
  backend/EasySpeak.Core/EasySpeak.Core.Common/DTO/User/UserDto.cs
  backend/EasySpeak.Core/EasySpeak.Core.Common/DTO/User/UserRegisterDto.cs
  backend/EasySpeak.Core/EasySpeak.Core.WebAPI/Validators/User/NewUserDtoValidator.cs
  frontend/package.json
  frontend/src/app/modules/auth/sign-up/sign-up.component.html
  frontend/src/app/modules/auth/sign-up/sign-up.component.ts
  frontend/src/app/shared/components/calendar/calendar.component.html
  frontend/src/app/shared/components/calendar/calendar.component.sass
  frontend/src/app/shared/components/calendar/calendar.component.ts
  frontend/src/app/shared/models/INewUser.ts
  frontend/yarn.lock
Labels: enhancement, bugfix

#128 156 real user profile photo
  frontend/src/app/modules/user-card/user-card.component.html
  frontend/src/app/modules/user-card/user-card.component.sass
  frontend/src/app/modules/user-card/user-card.component.ts
  frontend/src/app/modules/user-profile/user-details/user-details/user-details.component.html
  frontend/src/app/modules/user-profile/user-details/user-details/user-details.component.sass
  frontend/src/app/modules/user-profile/user-details/user-details/user-details.component.ts
  frontend/src/app/shared/components/avatar/avatar.component.html
  frontend/src/app/shared/components/avatar/avatar.component.sass
  frontend/src/app/shared/components/avatar/avatar.component.ts
  frontend/src/app/shared/components/header/header.component.html
  frontend/src/app/shared/components/header/header.component.sass
  frontend/src/app/shared/components/header/header.component.ts
Labels: bugfix

#153 fix padding between dialogue list and chat
  frontend/src/app/modules/chat/chat-page/chat-page.component.sass
Labels: bugfix

#154 Fixed display of time on lesson card
  frontend/src/app/modules/lessons/lesson/lesson.component.sass
Labels: bugfix

#159 189 Updated video functionality
  backend/EasySpeak.Core/EasySpeak.Core.WebAPI/Hubs/SignalRtcHub.cs
  frontend/src/app/core/hubs/webrtc-hub.service.ts
  frontend/src/app/core/services/auth.service.ts
  frontend/src/app/modules/chat/chat-page/chat-page.component.ts
  frontend/src/app/modules/session-call/session-call/session-call.component.html
  frontend/src/app/modules/session-call/session-call/session-call.component.sass
  frontend/src/app/modules/session-call/session-call/session-call.component.ts
  frontend/src/app/shared/components/accept-call/accept-call.component.html
  frontend/src/app/shared/components/accept-call/accept-call.component.sass
  frontend/src/app/shared/components/accept-call/accept-call.component.ts
  frontend/src/app/shared/components/header/header.component.ts
  frontend/src/app/shared/models/UserShort.ts
  frontend/src/app/shared/shared.module.ts
  frontend/src/assets/session-call/accept_icon.svg
  frontend/src/assets/session-call/avatar.svg
  frontend/src/assets/session-call/hangup_icon.svg
  frontend/src/assets/session-call/mic_icon.svg
  frontend/src/assets/session-call/reject_icon.svg
  frontend/src/assets/session-call/video_icon.svg
Labels: enhancement

#170 fixed teacher statistics displayed incorrectly
  backend/EasySpeak.Core/EasySpeak.Core.BLL/Services/LessonsService.cs
Labels: bugfix

#175 Change default YouTube thumbnail on the new one
  frontend/src/assets/lesson-icons/no-video.png
Labels: bugfix

#176 204-icons-on-landing-page
  frontend/src/app/modules/landing/landing-page/landing-page.component.sass
Labels: reviewed

#177 Fix bug with previously deleted option
  frontend/src/app/modules/social-page/filter-section/filter-section.component.ts
Labels: bugfix

#180 changed span text
  frontend/src/app/shared/components/header/header.component.html
Labels: bugfix

#181 220 Hide "Mark as read" button in notifications
  backend/EasySpeak.Core/EasySpeak.Core.BLL/Services/NotificationService.cs
  frontend/src/app/shared/components/user-notification/user-notification.component.html
  frontend/src/app/shared/components/user-notification/user-notification.component.ts
Labels: bugfix

#184 fixed a bug
  frontend/src/app/modules/chat/chat-page/chat-page.component.ts
Labels: bugfix

#185 Date of birth on User details tab/Sign up form is not centered vertically
  frontend/package.json
  frontend/src/app/modules/auth/sign-up/sign-up.component.sass
  frontend/src/app/modules/user-profile/user-details/user-details/user-details.component.sass
  frontend/yarn.lock
Labels: bugfix

#190 Add 'Forgot password' on Sign in page
  frontend/src/app/modules/auth/sign-in/sign-in.component.html
  frontend/src/app/modules/auth/sign-in/sign-in.component.sass
Labels: bugfix

#182 212 Fixed notifications sending
  backend/EasySpeak.Core/EasySpeak.Core.BLL/Services/FriendService.cs
  backend/EasySpeak.Core/EasySpeak.Core.BLL/Services/UserService.cs
  backend/EasySpeak.Notifier/EasySpeak.Notifier.WebAPI/Extentions/ServiceCollectionExtentions.cs
  backend/EasySpeak.Notifier/EasySpeak.Notifier.WebAPI/Hubs/NotificationHub.cs
  backend/EasySpeak.Notifier/EasySpeak.Notifier.WebAPI/Services/ConsumerHostedService.cs
  frontend/src/app/core/hubs/notifications-hub.service.ts
  frontend/src/app/core/services/auth.service.ts
  frontend/src/app/shared/components/user-notification/user-notification.component.ts
Labels: bugfix

#206 Fixed configurations for recommendations service inside appsettings a…
  backend/EasySpeak.Core/EasySpeak.Core.WebAPI/appsettings.json
  backend/EasySpeak.RecommendationService/EasySpeak.RS.WebAPI/appsettings.json
  docker-compose.apps.prod.yml
Labels: bugfix

#208 Added recommendator service's port
  README.md
Labels: enhancement

#198 198 long loading user info
  frontend/src/app/core/services/auth.service.ts
  frontend/src/app/modules/auth/sign-up/sign-up.component.ts
Labels: bugfix

#210 Added recommendator service's configs
  .github/workflows/continuous-delivery.yml
Labels: enhancement

#211 Fixed docker compose files and recommendator service's dockerfile
  backend/EasySpeak.RecommendationService/Dockerfile
  docker-compose.apps.prod.yml
  docker-compose.apps.yml
Labels: bugfix

#212 Updated dependencies for deploy_images
  .github/workflows/continuous-delivery.yml
Labels: bugfix

#214 Modified comfigurations for core project
  backend/EasySpeak.Core/EasySpeak.Core.WebAPI/appsettings.json
Labels: bugfix

#213 Bugfix lesson cards and teacher page
  frontend/src/app/modules/auth/sign-up/sign-up.component.ts
  frontend/src/app/modules/landing/landing-page/landing-page.component.sass
  frontend/src/app/modules/lessons/lesson/lesson.component.html
  frontend/src/app/modules/lessons/lesson/lesson.component.sass
  frontend/src/app/modules/user/teachers-page/teachers-page.component.html
  frontend/src/app/modules/user/teachers-page/teachers-page.component.ts
  frontend/src/app/shared/components/header/header.component.html
  frontend/src/app/shared/components/header/header.component.ts
  frontend/src/app/shared/models/IUserShort.ts
  frontend/src/assets/header/book-icon.svg
Labels: bugfix

#216 244: fix Youtube
  frontend/src/app/modules/lessons/lesson/lesson.component.ts
Labels: bugfix

#218 Fixed configs for recommendation service inside compose file
  docker-compose.services.prod.yml
  docker-compose.services.yml
Labels: bugfix

#215 192 create chats
  backend/EasySpeak.Core/EasySpeak.Core.BLL/Interfaces/IChatService.cs
  backend/EasySpeak.Core/EasySpeak.Core.BLL/Services/ChatService.cs
  backend/EasySpeak.Core/EasySpeak.Core.WebAPI/Controllers/ChatCotroller.cs
  frontend/src/app/core/services/chat.service.ts
  frontend/src/app/modules/chat/chat-page/chat-page.component.ts
  frontend/src/app/modules/chat/chat-routing.module.ts
  frontend/src/app/modules/user-card/user-card.component.html
  frontend/src/app/modules/user-card/user-card.component.ts
  frontend/src/app/shared/models/user/user-card.ts
Labels: enhancement

#220 Fixed docker-compose.apps.yml file
  backend/EasySpeak.Core/Dockerfile
  docker-compose.apps.yml
Labels: bugfix

#222 253 chat improvements
  backend/EasySpeak.Core/EasySpeak.Core.BLL/Services/ChatService.cs
  backend/EasySpeak.Core/EasySpeak.Core.Common/DTO/Message/ChatPersonDto.cs
  frontend/src/app/core/hubs/chat-hub.service.ts
  frontend/src/app/modules/chat/chat-page/chat-page.component.html
  frontend/src/app/modules/chat/chat-page/chat-page.component.sass
  frontend/src/app/modules/chat/chat-page/chat-page.component.ts
  frontend/src/app/modules/chat/message-group/message-group.component.html
  frontend/src/app/modules/chat/message-group/message-group.component.sass
  frontend/src/app/modules/chat/message-group/message-group.component.ts
  frontend/src/app/shared/components/avatar/avatar.component.html
  frontend/src/app/shared/models/chat/IChatPerson.ts
  frontend/src/app/shared/utils/time.utils.ts
  frontend/src/assets/chat/emoji.svg
Labels: enhancement

#229 Moving chat hub to notifier
  backend/EasySpeak.Core/EasySpeak.Core.BLL/Interfaces/IChatService.cs
  backend/EasySpeak.Core/EasySpeak.Core.BLL/Services/ChatService.cs
  backend/EasySpeak.Core/EasySpeak.Core.WebAPI/Controllers/ChatCotroller.cs
  backend/EasySpeak.Core/EasySpeak.Core.WebAPI/Hubs/ChatHub.cs
  backend/EasySpeak.Core/EasySpeak.Core.WebAPI/Program.cs
  backend/EasySpeak.Notifier/EasySpeak.Notifier.WebAPI/Hubs/ChatHub.cs
  backend/EasySpeak.Notifier/EasySpeak.Notifier.WebAPI/Program.cs
  frontend/src/app/core/hubs/chat-hub.service.ts
  frontend/src/app/core/hubs/notifications-hub.service.ts
  frontend/src/app/core/services/auth.service.ts
  frontend/src/app/core/services/chat.service.ts
  frontend/src/app/modules/chat/chat-page/chat-page.component.ts
  frontend/src/app/shared/components/header/header.component.html
  frontend/src/app/shared/components/header/header.component.ts
  frontend/src/app/shared/models/chat/IMessage.ts
Labels: bugfix

#228 Bugfix lesson card questions
  frontend/src/app/modules/lessons/lesson/lesson.component.html
  frontend/src/app/modules/lessons/lesson/lesson.component.sass
  frontend/src/app/modules/lessons/lesson/lesson.component.ts
  frontend/src/app/modules/lessons/lessons-page/lessons-page.component.html
  frontend/src/app/modules/lessons/lessons-page/lessons-page.component.ts
  frontend/src/app/modules/user-profile/user-details/user-details/user-details.component.sass
  frontend/src/app/modules/user/teachers-page/teachers-page.component.html
  frontend/src/app/modules/user/teachers-page/teachers-page.component.ts
Labels: bugfix

#233 251 lesson scheduler service
  backend/EasySpeak.Core/EasySpeak.Core.BLL/Interfaces/ILessonsService.cs
  backend/EasySpeak.Core/EasySpeak.Core.BLL/Interfaces/INotificationService.cs
  backend/EasySpeak.Core/EasySpeak.Core.BLL/Options/LessonSchedulerOptions.cs
  backend/EasySpeak.Core/EasySpeak.Core.BLL/Services/FriendService.cs
  backend/EasySpeak.Core/EasySpeak.Core.BLL/Services/LessonSchedulerService.cs
  backend/EasySpeak.Core/EasySpeak.Core.BLL/Services/LessonsService.cs
  backend/EasySpeak.Core/EasySpeak.Core.BLL/Services/NotificationService.cs
  backend/EasySpeak.Core/EasySpeak.Core.Common/DTO/Lesson/LessonDelayDto.cs
  backend/EasySpeak.Core/EasySpeak.Core.WebAPI/Extensions/ServiceCollectionExtensions.cs
  backend/EasySpeak.Core/EasySpeak.Core.WebAPI/appsettings.json
  backend/EasySpeak.Notifier/EasySpeak.Notifier.WebAPI/Hubs/NotificationHub.cs
  frontend/src/app/core/hubs/notifications-hub.service.ts
  frontend/src/app/core/services/auth.service.ts
  frontend/src/app/shared/components/user-notification/user-notification.component.ts
Labels: enhancement

#240 222 fixed notifications time to user's local time
  frontend/src/app/shared/components/user-notification/user-notification.component.ts
Labels: bugfix

#242 Fix avatar loading when user is undefined
  frontend/src/app/shared/components/header/header.component.html
Labels: bugfix

#246 269-289: Teacher can't join his own lessons
  backend/EasySpeak.Core/EasySpeak.Core.Common/DTO/Lesson/UserForLessonDto.cs
  frontend/src/app/modules/lessons/lesson/lesson.component.html
  frontend/src/app/modules/lessons/lesson/lesson.component.ts
  frontend/src/app/modules/user-profile/user-details/user-details/user-details.component.sass
  frontend/src/app/modules/user-profile/user-password-change/user-password-change.component.sass
  frontend/src/app/shared/models/lesson/ILessonUser.ts
Labels: bugfix

#250 233 Fixed wrong behaviour on lesson join for notifications
  backend/EasySpeak.Core/EasySpeak.Core.BLL/Interfaces/ILessonsService.cs
  backend/EasySpeak.Core/EasySpeak.Core.BLL/Services/FriendService.cs
  backend/EasySpeak.Core/EasySpeak.Core.BLL/Services/LessonSchedulerService.cs
  backend/EasySpeak.Core/EasySpeak.Core.BLL/Services/NotificationService.cs
  backend/EasySpeak.Notifier/EasySpeak.Notifier.WebAPI/Hubs/NotificationHub.cs
  frontend/src/app/core/services/auth.service.ts
  frontend/src/app/shared/components/user-notification/user-notification.component.html
  frontend/src/app/shared/components/user-notification/user-notification.component.ts
Labels: bugfix

#251 Fixed compatibility constraint and user update for neo4j
  backend/EasySpeak.Core/EasySpeak.Core.BLL/Services/QueriesSenderService.cs
  backend/EasySpeak.Core/EasySpeak.Core.BLL/Services/UserService.cs
  backend/EasySpeak.RecommendationService/EasySpeak.RS.WebAPI/Helpers/QueryHelper.cs
  backend/EasySpeak.RecommendationService/EasySpeak.RS.WebAPI/Services/RecommendationService.cs
Labels: bugfix
