Repository BinaryStudioAcademy/bsa-winter-2022-2023-easyspeak, pull requests merged in 2023-03, with the labels that each got.

#1 adding color css variables
  frontend/src/styles/colors.sass
Labels: enhancement

#6 Adding topic select page
  frontend/src/app/modules/user-profile/select-topics-page/select-topics-page.component.html
  frontend/src/app/modules/user-profile/select-topics-page/select-topics-page.component.sass
  frontend/src/app/modules/user-profile/select-topics-page/select-topics-page.component.ts
  frontend/src/app/modules/user-profile/user-profile-routing.module.ts
  frontend/src/app/modules/user-profile/user-profile.module.ts
  frontend/src/app/shared/data/topics.ts
  frontend/src/app/shared/models/ITopic.ts
  frontend/src/assets/brackets/Icon.svg
  frontend/src/assets/fonts/Barlow-Medium.ttf
  frontend/src/assets/topic-icons/Artist Palette.svg
  frontend/src/assets/topic-icons/Artist.svg
  frontend/src/assets/topic-icons/Camera.svg
  frontend/src/assets/topic-icons/Classical Building.svg
  frontend/src/assets/topic-icons/Cook.svg
  frontend/src/assets/topic-icons/Crossed Swords.svg
  frontend/src/assets/topic-icons/Crown.svg
  frontend/src/assets/topic-icons/Dog Face.svg
  frontend/src/assets/topic-icons/Dress.svg
  frontend/src/assets/topic-icons/Face With Monocle.svg
  frontend/src/assets/topic-icons/Four Leaf Clover.svg
  frontend/src/assets/topic-icons/Pill.svg
  frontend/src/assets/topic-icons/Racing Car.svg
  frontend/src/assets/topic-icons/Robot.svg
  frontend/src/assets/topic-icons/Woman Dancing.svg
  frontend/src/styles/colors.sass
  frontend/src/styles/global.sass
Labels: enhancement

#27 22 basic chat created
  frontend/src/app/modules/chat/chat-page/chat-page.component.html
  frontend/src/app/modules/chat/chat-page/chat-page.component.sass
  frontend/src/app/modules/chat/chat-page/chat-page.component.ts
  frontend/src/app/modules/chat/chat-routing.module.ts
  frontend/src/app/modules/chat/chat.module.ts
Labels: enhancement, approved

#26 33 get userId from tocken
  backend/EasySpeak.Core/EasySpeak.Core.BLL/Interfaces/IFirebaseAuthService.cs
  backend/EasySpeak.Core/EasySpeak.Core.BLL/Services/FirebaseAuthService.cs
  backend/EasySpeak.Core/EasySpeak.Core.WebAPI/Controllers/AuthenticationTestController.cs
  backend/EasySpeak.Core/EasySpeak.Core.WebAPI/EasySpeak.Core.WebAPI.csproj
  backend/EasySpeak.Core/EasySpeak.Core.WebAPI/Extentions/ServiceCollectionExtensions.cs
  backend/EasySpeak.Core/EasySpeak.Core.WebAPI/Middlewares/FirebaseAuthMiddleware.cs
  backend/EasySpeak.Core/EasySpeak.Core.WebAPI/Program.cs
Labels: reviewed

#23 authorization page
  frontend/.browserslistrc
  frontend/.vscode/settings.json
  frontend/src/app/app-routing.module.ts
  frontend/src/app/app.module.ts
  frontend/src/app/modules/auth/auth-page/auth-page.component.html
  frontend/src/app/modules/auth/auth-page/auth-page.component.sass
  frontend/src/app/modules/auth/auth-page/auth-page.component.ts
  frontend/src/app/modules/auth/auth-routing.module.ts
  frontend/src/app/modules/auth/auth.module.ts
  frontend/src/app/modules/auth/sign-in/sign-in.component.html
  frontend/src/app/modules/auth/sign-in/sign-in.component.sass
  frontend/src/app/modules/auth/sign-in/sign-in.component.ts
  frontend/src/app/modules/auth/sign-up/sign-up.component.html
  frontend/src/app/modules/auth/sign-up/sign-up.component.sass
  frontend/src/app/modules/auth/sign-up/sign-up.component.ts
  frontend/src/app/modules/user-profile/select-topics-page/select-topics-page.component.ts
  frontend/src/test.ts
Labels: reviewed

#30 41 added global font, removed references to font from local files
  frontend/src/app/modules/auth/auth-page/auth-page.component.sass
  frontend/src/app/modules/lessons/lessons-page/lessons-page.component.sass
  frontend/src/app/modules/user-profile/select-topics-page/select-topics-page.component.sass
  frontend/src/app/shared/components/header/header.component.sass
  frontend/src/styles/global.sass
Labels: reviewed

#12 25 firebase frontend
  frontend/package.json
  frontend/src/app/app.module.ts
  frontend/src/app/core/services/auth.service.ts
  frontend/src/app/shared/models/IUser.ts
  frontend/src/environments/environment.prod.ts
  frontend/src/environments/environment.ts
  frontend/tsconfig.json
  frontend/yarn.lock
Labels: enhancement, reviewed

#21 28 rabbitmq queue
  backend/EasySpeak.All.sln
  backend/EasySpeak.Core/Dockerfile
  backend/EasySpeak.Core/EasySpeak.Core.WebAPI/Controllers/SampleController.cs
  backend/EasySpeak.Core/EasySpeak.Core.WebAPI/EasySpeak.Core.WebAPI.csproj
  backend/EasySpeak.Core/EasySpeak.Core.WebAPI/Extentions/ServiceCollectionExtensions.cs
  backend/EasySpeak.Core/EasySpeak.Core.WebAPI/Program.cs
  backend/EasySpeak.Core/EasySpeak.Core.WebAPI/appsettings.json
  backend/EasySpeak.Notifier/Dockerfile
  backend/EasySpeak.Notifier/EasySpeak.Notifier.WebAPI/EasySpeak.Notifier.WebAPI.csproj
  backend/EasySpeak.Notifier/EasySpeak.Notifier.WebAPI/Extentions/ServiceCollectionExtentions.cs
  backend/EasySpeak.Notifier/EasySpeak.Notifier.WebAPI/Program.cs
  backend/EasySpeak.Notifier/EasySpeak.Notifier.WebAPI/Services/ConsumerHostedService.cs
  backend/EasySpeak.Notifier/EasySpeak.Notifier.WebAPI/appsettings.json
  backend/EasySpeak.RabbitMQ/ConnectionProvider.cs
  backend/EasySpeak.RabbitMQ/EasySpeak.RabbitMQ.csproj
  backend/EasySpeak.RabbitMQ/Interfaces/IConnectionProvider.cs
  backend/EasySpeak.RabbitMQ/Interfaces/IMessageConsumer.cs
  backend/EasySpeak.RabbitMQ/Interfaces/IMessageProducer.cs
  backend/EasySpeak.RabbitMQ/Services/MessageConsumer.cs
  backend/EasySpeak.RabbitMQ/Services/MessageProducer.cs
Labels: reviewed

#13 12 Implemented filter section component
  frontend/src/app/components/dropdown/dropdown.component.html
  frontend/src/app/components/dropdown/dropdown.component.sass
  frontend/src/app/components/dropdown/dropdown.component.ts
  frontend/src/app/components/filter-section/filter-section.component.html
  frontend/src/app/components/filter-section/filter-section.component.sass
  frontend/src/app/components/filter-section/filter-section.component.ts
  frontend/src/app/components/filter-section/filter-section.util.ts
  frontend/src/app/models/filters/filter.ts
Labels: enhancement, reviewed

#20 10 a suitable lesson section
  frontend/package.json
  frontend/src/app/modules/time-table/material/material.module.ts
  frontend/src/app/modules/time-table/suitable-lesson-day/suitable-lesson-day.component.html
  frontend/src/app/modules/time-table/suitable-lesson-day/suitable-lesson-day.component.sass
  frontend/src/app/modules/time-table/suitable-lesson-day/suitable-lesson-day.component.ts
  frontend/src/app/modules/time-table/suitable-lesson/suitable-lesson.component.html
  frontend/src/app/modules/time-table/suitable-lesson/suitable-lesson.component.sass
  frontend/src/app/modules/time-table/suitable-lesson/suitable-lesson.component.ts
  frontend/src/app/modules/time-table/time-table.module.ts
  frontend/src/index.html
  frontend/src/styles/colors.sass
  frontend/yarn.lock
Labels: reviewed

#31 40 Created backend validation for user inputs
  backend/EasySpeak.Core/EasySpeak.Core.Common/DTO/Lesson/NewLessonDto.cs
  backend/EasySpeak.Core/EasySpeak.Core.Common/DTO/Message/NewMessageDto.cs
  backend/EasySpeak.Core/EasySpeak.Core.Common/DTO/Question/NewQuestionDto.cs
  backend/EasySpeak.Core/EasySpeak.Core.Common/DTO/Subquestion/NewSubquestionDto.cs
  backend/EasySpeak.Core/EasySpeak.Core.Common/DTO/User/NewUserDto.cs
  backend/EasySpeak.Core/EasySpeak.Core.WebAPI/Validators/Lesson/NewLessonDtoValidator.cs
  backend/EasySpeak.Core/EasySpeak.Core.WebAPI/Validators/Message/NewMessageDtoValidator.cs
  backend/EasySpeak.Core/EasySpeak.Core.WebAPI/Validators/Question/NewQuestionDtoValidator.cs
  backend/EasySpeak.Core/EasySpeak.Core.WebAPI/Validators/Subquestion/NewSubquestionDtoValidator.cs
  backend/EasySpeak.Core/EasySpeak.Core.WebAPI/Validators/User/NewUserDtoValidator.cs
Labels: enhancement

#32 46 Made Dropdown component shared
  frontend/src/app/modules/filter-section/filter-section.module.ts
  frontend/src/app/modules/filter-section/filter-section/filter-section.component.html
  frontend/src/app/modules/filter-section/filter-section/filter-section.component.sass
  frontend/src/app/modules/filter-section/filter-section/filter-section.component.ts
  frontend/src/app/modules/filter-section/filter-section/filter-section.util.ts
  frontend/src/app/shared/components/dropdown/dropdown.component.html
  frontend/src/app/shared/components/dropdown/dropdown.component.sass
  frontend/src/app/shared/components/dropdown/dropdown.component.ts
  frontend/src/app/shared/shared.module.ts
Labels: enhancement

#34 39 modal confirmation component
  frontend/src/app/shared/components/confirm/confirm.component.html
  frontend/src/app/shared/components/confirm/confirm.component.sass
  frontend/src/app/shared/components/confirm/confirm.component.ts
  frontend/src/app/shared/components/modal/modal.component.html
  frontend/src/app/shared/components/modal/modal.component.sass
  frontend/src/app/shared/components/modal/modal.component.ts
  frontend/src/app/shared/models/IConfirm.ts
  frontend/src/app/shared/models/IModal.ts
  frontend/src/app/shared/shared.module.ts
Labels: enhancement

#38 adding icon and title
  frontend/src/assets/logo/logo.svg
  frontend/src/favicon.ico
  frontend/src/index.html
Labels: enhancement

#39 31 Ability to create lessons
  backend/EasySpeak.Core/EasySpeak.Core.BLL/Interfaces/ILessonsService.cs
  backend/EasySpeak.Core/EasySpeak.Core.BLL/MappingProfiles/LessonsProfile.cs
  backend/EasySpeak.Core/EasySpeak.Core.BLL/MappingProfiles/QuestionsProfile.cs
  backend/EasySpeak.Core/EasySpeak.Core.BLL/MappingProfiles/SubQuestionsProfile.cs
  backend/EasySpeak.Core/EasySpeak.Core.BLL/MappingProfiles/TagForLessonProfile.cs
  backend/EasySpeak.Core/EasySpeak.Core.BLL/Services/LessonsService.cs
  backend/EasySpeak.Core/EasySpeak.Core.Common/DTO/Lesson/NewLessonDto.cs
  backend/EasySpeak.Core/EasySpeak.Core.Common/DTO/Lesson/QuestionForLessonDto.cs
  backend/EasySpeak.Core/EasySpeak.Core.Common/DTO/Lesson/SubQuestionDto.cs
  backend/EasySpeak.Core/EasySpeak.Core.Common/DTO/Lesson/TagForLessonDto.cs
  backend/EasySpeak.Core/EasySpeak.Core.WebAPI/Controllers/LessonsController.cs
  frontend/src/app/modules/lessons/lessons-create/lessons-create.component.html
  frontend/src/app/modules/lessons/lessons-create/lessons-create.component.sass
  frontend/src/app/modules/lessons/lessons-create/lessons-create.component.ts
  frontend/src/app/modules/lessons/lessons-page/lessons-page.component.ts
  frontend/src/app/modules/lessons/lessons.module.ts
  frontend/src/app/modules/material/material-routing.module.ts
  frontend/src/app/modules/material/material.module.ts
  frontend/src/app/services/lessons.service.ts
  frontend/src/app/shared/models/lesson/INewLesson.ts
  frontend/src/app/shared/models/lesson/INewQuestion.ts
  frontend/src/app/shared/models/lesson/INewSubquestion.ts
  frontend/src/app/shared/models/lesson/INewTag.ts
  frontend/src/app/shared/utils/lesson.utils.ts
Labels: enhancement

#35 24 endpoints get lessons by dates
  backend/EasySpeak.Core/EasySpeak.Core.BLL/Interfaces/ILessonsService.cs
  backend/EasySpeak.Core/EasySpeak.Core.BLL/Services/LessonsService.cs
  backend/EasySpeak.Core/EasySpeak.Core.Common/DTO/Lesson/DayCardDto.cs
  backend/EasySpeak.Core/EasySpeak.Core.Common/DTO/Lesson/RequestDayCardDto.cs
  backend/EasySpeak.Core/EasySpeak.Core.WebAPI/Controllers/LessonsController.cs
Labels: enhancement

#43 53 material module shared
  frontend/src/app/modules/auth/auth.module.ts
  frontend/src/app/modules/filter-section/filter-section.module.ts
  frontend/src/app/modules/lessons/lessons.module.ts
  frontend/src/app/modules/main/main.module.ts
  frontend/src/app/modules/time-table/material/material.module.ts
  frontend/src/app/modules/time-table/time-table.module.ts
  frontend/src/app/shared/material/material-routing.module.ts
  frontend/src/app/shared/material/material.module.ts
  frontend/src/app/shared/shared.module.ts
Labels: enhancement

#41 47 user card
  frontend/src/app/modules/auth/auth-page/auth-page.component.sass
  frontend/src/app/modules/auth/sign-up/sign-up.component.sass
  frontend/src/app/modules/filter-section/filter-section/filter-section.component.sass
  frontend/src/app/modules/lessons/lessons-create/lessons-create.component.sass
  frontend/src/app/modules/lessons/lessons-page/lessons-page.component.sass
  frontend/src/app/modules/time-table/suitable-lesson-day/suitable-lesson-day.component.sass
  frontend/src/app/modules/time-table/suitable-lesson/suitable-lesson.component.sass
  frontend/src/app/modules/user-card/user-card.component.html
  frontend/src/app/modules/user-card/user-card.component.sass
  frontend/src/app/modules/user-card/user-card.component.ts
  frontend/src/app/modules/user-card/user-card.module.ts
  frontend/src/app/modules/user-profile/select-topics-page/select-topics-page.component.sass
  frontend/src/app/shared/components/confirm/confirm.component.sass
  frontend/src/app/shared/components/dropdown/dropdown.component.sass
  frontend/src/app/shared/components/header/header.component.sass
  frontend/src/app/shared/components/modal/modal.component.sass
  frontend/src/app/shared/components/round-progress-bar/round-progress-bar.component.html
  frontend/src/app/shared/components/round-progress-bar/round-progress-bar.component.sass
  frontend/src/app/shared/components/round-progress-bar/round-progress-bar.component.ts
  frontend/src/app/shared/components/youtube-player/youtube-player.component.sass
  frontend/src/app/shared/models/user/user-card.ts
  frontend/src/app/shared/shared.module.ts
  frontend/src/app/shared/utils/user-card.utils.ts
  frontend/src/assets/user-card-icons/Photo.png
  frontend/src/assets/user-card-icons/canada-flag.svg
  frontend/src/assets/user-card-icons/clock-icon.svg
  frontend/src/assets/user-card-icons/facebook.svg
  frontend/src/assets/user-card-icons/follow-icon.svg
  frontend/src/assets/user-card-icons/instagram.svg
  frontend/src/assets/user-card-icons/rocket-icon.svg
  frontend/src/styles/colors.sass
Labels: enhancement

#40 42 Implemented UserProfile component
  backend/EasySpeak.Core/EasySpeak.Core.BLL/Interfaces/IUserService.cs
  backend/EasySpeak.Core/EasySpeak.Core.BLL/MappingProfiles/UserProfile.cs
  backend/EasySpeak.Core/EasySpeak.Core.BLL/Services/UserService.cs
  backend/EasySpeak.Core/EasySpeak.Core.Common/DTO/User/UserDto.cs
  backend/EasySpeak.Core/EasySpeak.Core.DAL/EasySpeak.Core.DAL.csproj
  backend/EasySpeak.Core/EasySpeak.Core.DAL/Entities/User.cs
  backend/EasySpeak.Core/EasySpeak.Core.WebAPI/Controllers/UserController.cs
  frontend/package.json
  frontend/src/app/app.module.ts
  frontend/src/app/core/services/user.service.ts
  frontend/src/app/modules/lessons/lessons-page/lessons-page.component.html
  frontend/src/app/modules/user-profile/user-details/user-details.component.util.ts
  frontend/src/app/modules/user-profile/user-details/user-details/user-details.component.html
  frontend/src/app/modules/user-profile/user-details/user-details/user-details.component.sass
  frontend/src/app/modules/user-profile/user-details/user-details/user-details.component.ts
  frontend/src/app/modules/user-profile/user-password-change/user-password-change.component.html
  frontend/src/app/modules/user-profile/user-password-change/user-password-change.component.sass
  frontend/src/app/modules/user-profile/user-password-change/user-password-change.component.ts
  frontend/src/app/modules/user-profile/user-profile-page/user-profile-page.component.html
  frontend/src/app/modules/user-profile/user-profile-page/user-profile-page.component.sass
  frontend/src/app/modules/user-profile/user-profile-page/user-profile-page.component.ts
  frontend/src/app/modules/user-profile/user-profile-routing.module.ts
  frontend/src/app/modules/user-profile/user-profile.module.ts
  frontend/src/app/modules/user-profile/user-subscription/user-subscription.component.html
  frontend/src/app/modules/user-profile/user-subscription/user-subscription.component.sass
  frontend/src/app/modules/user-profile/user-subscription/user-subscription.component.ts
  frontend/src/app/shared/data/ages.util.ts
  frontend/src/app/shared/data/englishLevel.ts
  frontend/src/app/shared/data/sex.ts
  frontend/src/app/shared/models/IUserInfo.ts
  frontend/src/app/shared/shared.module.ts
  frontend/src/assets/user-profile/alert-triangle.svg
  frontend/src/assets/user-profile/avatar.svg
  frontend/src/assets/user-profile/boy.svg
  frontend/src/assets/user-profile/edit-icon.svg
  frontend/src/assets/user-profile/man-bald.svg
  frontend/src/assets/user-profile/man-beard.svg
  frontend/src/assets/user-profile/man-curly.svg
  frontend/src/assets/user-profile/man-elf.svg
  frontend/src/assets/user-profile/man-in-tuxedo.svg
  frontend/src/assets/user-profile/man-red-hair.svg
  frontend/src/assets/user-profile/man-superhero.svg
  frontend/src/assets/user-profile/man-technologist.svg
  frontend/src/assets/user-profile/man-white-hair.svg
  frontend/src/styles/colors.sass
  frontend/yarn.lock
Labels: enhancement

#61 51 fully functional main page
  backend/EasySpeak.Core/EasySpeak.Core.BLL/Services/LessonsService.cs
  frontend/src/app/core/services/http.service.ts
  frontend/src/app/modules/filter-section/filter-section/filter-section.component.ts
  frontend/src/app/modules/filter-section/filter-section/filter-section.util.ts
  frontend/src/app/modules/lessons/lessons-page/lessons-page.component.html
  frontend/src/app/modules/lessons/lessons-page/lessons-page.component.sass
  frontend/src/app/modules/lessons/lessons-page/lessons-page.component.ts
  frontend/src/app/modules/main/timetable-page/timetable-page.component.html
  frontend/src/app/modules/main/timetable-page/timetable-page.component.ts
  frontend/src/app/modules/time-table/suitable-lesson-day/suitable-lesson-day.component.html
  frontend/src/app/modules/time-table/suitable-lesson-day/suitable-lesson-day.component.sass
  frontend/src/app/modules/time-table/suitable-lesson-day/suitable-lesson-day.component.ts
  frontend/src/app/modules/time-table/suitable-lesson/suitable-lesson.component.html
  frontend/src/app/modules/time-table/suitable-lesson/suitable-lesson.component.ts
  frontend/src/app/services/lessons.service.ts
  frontend/src/app/shared/models/lesson/IFilter.ts
  frontend/src/app/shared/models/lesson/ILesson.ts
  frontend/src/app/shared/models/lesson/IQuestion.ts
  frontend/src/app/shared/models/lesson/ITag.ts
  frontend/src/app/shared/models/lesson/LanguageLevels.ts
Labels: enhancement

#62 fix
  frontend/src/app/modules/auth/auth-page/auth-page.component.sass
  frontend/src/app/modules/auth/sign-in/sign-in.component.sass
  frontend/src/app/modules/auth/sign-up/sign-up.component.sass
Labels: bug

#64 65 Added routing for all components
  frontend/src/app/app-routing.module.ts
  frontend/src/app/modules/main/main-routing.module.ts
  frontend/src/app/modules/main/main.module.ts
  frontend/src/app/modules/user-profile/user-profile-page/user-profile-page.component.html
  frontend/src/app/modules/user-profile/user-profile-page/user-profile-page.component.sass
  frontend/src/app/shared/components/header/header.component.html
  frontend/src/app/shared/components/header/header.component.sass
Labels: enhancement

#48 57 Defined enums and implemented mapping for them
  backend/EasySpeak.Core/EasySpeak.Core.BLL/Converters/Enum/EnumToStringConverter.cs
  backend/EasySpeak.Core/EasySpeak.Core.BLL/Converters/Enum/StringToEnumConverter.cs
  backend/EasySpeak.Core/EasySpeak.Core.BLL/Helpers/EnumHelper.cs
  backend/EasySpeak.Core/EasySpeak.Core.BLL/Helpers/EnumMappingHelper.cs
  backend/EasySpeak.Core/EasySpeak.Core.BLL/MappingProfiles/CountriesProfile.cs
  backend/EasySpeak.Core/EasySpeak.Core.BLL/MappingProfiles/LanguagesProfile.cs
  backend/EasySpeak.Core/EasySpeak.Core.BLL/MappingProfiles/TimezonesProfile.cs
  backend/EasySpeak.Core/EasySpeak.Core.BLL/MappingProfiles/UserProfile.cs
  backend/EasySpeak.Core/EasySpeak.Core.Common/Enums/Country.cs
  backend/EasySpeak.Core/EasySpeak.Core.Common/Enums/Language.cs
  backend/EasySpeak.Core/EasySpeak.Core.Common/Enums/Timezone.cs
  backend/EasySpeak.Core/EasySpeak.Core.WebAPI/Extentions/ServiceCollectionExtensions.cs
  backend/EasySpeak.Core/EasySpeak.Core.WebAPI/Program.cs
  backend/EasySpeak.Core/EasySpeak.Core.WebAPI/Validators/User/NewUserDtoValidator.cs
  frontend/src/app/modules/auth/sign-up/sign-up.component.ts
  frontend/src/app/shared/models/ICountry.ts
Labels: enhancement

#76 fixing a bug
  frontend/src/app/modules/auth/sign-up/sign-up.component.ts
Labels: bug

#80 71 Created directive to show and hide password
  frontend/src/app/modules/auth/sign-in/sign-in.component.html
  frontend/src/app/modules/auth/sign-up/sign-up.component.html
  frontend/src/app/shared/directives/password-visibility.directive.ts
  frontend/src/app/shared/shared.module.ts
  frontend/src/assets/password-visibility/closed-eye.svg
  frontend/src/assets/password-visibility/opened-eye.svg
Labels: enhancement

#63 81 Fixed spinner when loading questions
  frontend/src/app/modules/lessons/lesson/lesson.component.html
  frontend/src/app/modules/lessons/lesson/lesson.component.sass
  frontend/src/app/modules/lessons/lesson/lesson.component.ts
  frontend/src/app/modules/lessons/lessons.module.ts
  frontend/src/app/shared/components/loading-spinner/loading-spinner.component.html
  frontend/src/app/shared/components/loading-spinner/loading-spinner.component.ts
  frontend/src/styles/loader.sass
Labels: bug

#86 adding not-found page and changing routes
  frontend/src/app/app-routing.module.ts
  frontend/src/app/core/guards/auth.guard.ts
  frontend/src/app/modules/main/main.module.ts
  frontend/src/app/shared/components/not-found/not-found.component.html
  frontend/src/app/shared/components/not-found/not-found.component.sass
  frontend/src/app/shared/shared.module.ts
Labels: enhancement

#87 fixed a bug with vertical align items in dropdown list by center
  frontend/src/app/shared/components/header/header.component.sass
Labels: bug

#89 the word 'meeting' is shown in the singular - 1 meeting
  frontend/src/app/modules/time-table/suitable-lesson-day/suitable-lesson-day.component.html
  frontend/src/app/modules/time-table/suitable-lesson-day/suitable-lesson-day.component.ts
Labels: bug

#97 fix ai section on landing page
  frontend/src/app/modules/landing/landing-page/landing-page.component.html
  frontend/src/app/modules/landing/landing-page/landing-page.component.sass
Labels: bug

#85 88 Completed auth flow
  backend/EasySpeak.Core/EasySpeak.Core.BLL/Interfaces/IUserService.cs
  backend/EasySpeak.Core/EasySpeak.Core.BLL/MappingProfiles/TagProfile.cs
  backend/EasySpeak.Core/EasySpeak.Core.BLL/MappingProfiles/UserProfile.cs
  backend/EasySpeak.Core/EasySpeak.Core.BLL/Services/LessonsService.cs
  backend/EasySpeak.Core/EasySpeak.Core.BLL/Services/UserService.cs
  backend/EasySpeak.Core/EasySpeak.Core.Common/DTO/Tag/TagDto.cs
  backend/EasySpeak.Core/EasySpeak.Core.Common/DTO/User/UserDto.cs
  backend/EasySpeak.Core/EasySpeak.Core.DAL/Entities/User.cs
  backend/EasySpeak.Core/EasySpeak.Core.WebAPI/Controllers/UserController.cs
  frontend/src/app/core/services/auth.service.ts
  frontend/src/app/core/services/user.service.ts
  frontend/src/app/modules/auth/auth-page/auth-page.component.html
  frontend/src/app/modules/auth/auth-page/auth-page.component.sass
  frontend/src/app/modules/auth/sign-in/sign-in.component.html
  frontend/src/app/modules/auth/sign-in/sign-in.component.sass
  frontend/src/app/modules/auth/sign-in/sign-in.component.ts
  frontend/src/app/modules/auth/sign-up/error-helper.ts
  frontend/src/app/modules/auth/sign-up/matchpassword.validator.ts
  frontend/src/app/modules/auth/sign-up/sign-up.component.html
  frontend/src/app/modules/auth/sign-up/sign-up.component.sass
  frontend/src/app/modules/auth/sign-up/sign-up.component.ts
  frontend/src/app/modules/user-profile/select-topics-page/select-topics-page.component.html
  frontend/src/app/modules/user-profile/select-topics-page/select-topics-page.component.ts
  frontend/src/app/shared/data/regex.util.ts
  frontend/src/app/shared/models/IUserInfo.ts
Labels: enhancement

#105 104 Bugfix topic icons display
  frontend/src/app/shared/data/topics.ts
Labels: bugfix

#75 CloseAll-button-visibility
  frontend/src/app/modules/filter-section/filter-section/filter-section.component.html
  frontend/src/app/modules/filter-section/filter-section/filter-section.component.ts
  frontend/src/app/modules/lessons/lessons-page/lessons-page.component.html
  frontend/src/app/modules/lessons/lessons-page/lessons-page.component.ts
  frontend/src/assets/lesson-mocks/test-user.png
Labels: enhancement

#95 Added chat page
  frontend/src/app/modules/chat/chat-page/chat-page.component.html
  frontend/src/app/modules/chat/chat-page/chat-page.component.sass
  frontend/src/app/modules/chat/chat-page/chat-page.component.ts
  frontend/src/app/modules/chat/chat.module.ts
  frontend/src/app/modules/chat/message-group/message-group.component.html
  frontend/src/app/modules/chat/message-group/message-group.component.sass
  frontend/src/app/modules/chat/message-group/message-group.component.ts
  frontend/src/app/shared/models/IChatPerson.ts
  frontend/src/app/shared/models/IMessage.ts
  frontend/src/assets/chat/Camera.svg
  frontend/src/assets/chat/More-input.svg
  frontend/src/assets/chat/More.svg
  frontend/src/assets/chat/Pin.svg
  frontend/src/assets/chat/ReadMessage.svg
  frontend/src/styles/colors.sass
Labels: enhancement

#106 123 returned password visibility button, updated it's styles
  frontend/src/app/modules/auth/sign-in/sign-in.component.html
  frontend/src/app/modules/auth/sign-up/sign-up.component.html
  frontend/src/app/shared/directives/password-visibility.directive.ts
Labels: bugfix

#103 121 fixed bug when user cannot enter if it is not added to db
  backend/EasySpeak.Core/EasySpeak.Core.BLL/Interfaces/IUserService.cs
  backend/EasySpeak.Core/EasySpeak.Core.BLL/Services/UserService.cs
  backend/EasySpeak.Core/EasySpeak.Core.WebAPI/Controllers/UserController.cs
  frontend/src/app/core/services/auth.service.ts
  frontend/src/app/shared/components/header/header.component.html
  frontend/src/app/shared/components/header/header.component.ts
Labels: bugfix

#108 124 tags width fixed,duplicates are deleted
  frontend/src/app/modules/user-card/user-card.component.sass
  frontend/src/app/modules/user-card/user-card.component.ts
Labels: bugfix

#112 Update authpage input styles
  frontend/src/app/modules/auth/auth-page/auth-page.component.sass
  frontend/src/app/shared/directives/password-visibility.directive.ts
Labels: bugfix
